### ISSUE TITLE
provide verbose logging

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/rivine#39]
Right now it is very difficult to follow the flow of a certain chain of actions.

For example, when debugging the gateway module, to see why certain peers get added, others get dropped, or why peers seem to be stuck in a adding loop, it is right now impossible to follow that flow, without manually putting print statements, or going with GDB manually through it.

I think it would be useful if we provide a verbose flag to the daemon, which if passed, would log verbosely the program flow as it happens. This would require us to add such verbose (conditional) logging statements to each module. We could start with the Gateway module and expand from there. Just to see how much it really helps in understanding a situation/flow.

**Comment by robvanmieghem** [comment]
Add debug logging to the blockcreator module #487
