### ISSUE TITLE
Move the explorer frontend to the main rivine repo

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#436]
https://github.com/rivine/explorer similar to https://github.com/threefoldfoundation/tfchain/tree/master/frontend/explorer

**Comment by GlenDC** [comment]
When we discussed this last time, months ago, we decided to embed it in the tfchain repo because we had no easy solution to make it generic.

What is the approach you want to take here, such that we can make use of it in tfchain?

**Comment by GlenDC** [comment]
Moved to <https://github.com/threefoldtech/rivine-chain-explorer/tree/plainjs> as a template for the RivineCG tool.
