### ISSUE TITLE
check if we can encode a rivine adress in an eth address 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#460]

**Comment by LeeSmet** [comment]
An eth address is 20 bytes, so 40 hex characters (42 if the `0x` prefix is included). Given that a rivine address is 32 bytes, that won't work. 

Another approach would be to generate the eth address from the public key in rivine. That would allow block creators to track the contract transactions, and create the TFT's to the address on the rivine chain. The tokens can then be spend as any regular tokens as we have the matching keys (would be a separate output type ofc).

**Comment by robvanmieghem** [comment]
so no
