### ISSUE TITLE
Explain rivine Technical details to Weynand

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#464]
He can help in creating more commercial documentation

**Comment by robvanmieghem** [comment]
planned for Thursday  november 22

**Comment by GlenDC** [comment]
How did it go @robvanmieghem?

**Comment by GlenDC** [comment]
What's going to happen with this issue, given the planned meeting didn't go through?

**Comment by GlenDC** [comment]
Should this issue be also closed than, given that https://github.com/threefoldtech/home/issues/33 is also closed? Or are these issues unrelated?

**Comment by robvanmieghem** [comment]
explained the techincal details of the pobs protocol
