### ISSUE TITLE
is it OK that miner fees are currently opt-out in v1 transactions

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/rivine#504]
We do validate that when miner fees are defined, that they are equal to or higher than the minimum value.  We also check for a block if the sum of all fees are as expected. However the expected sum really just takes into account the fees that are defined, meaning if you don't define any fee, it will just happily accept this.

In order to reproduce this, try to create a custom transaction using a script or CLI, sign it, and send it, you'll see it will accept a transaction without having to sign it. (Note that when using CLI you will have to modify the created transaction a bit, as our code for creating a coin transaction does validate, but that is not the official validation, so as long as you avoid that, you can happily sign and push a transaction without paid miner fees into the blockchain.

That this bug (feature?:) has remained undetected for so long is surprising to say the least. Until now this hasn't been an issue as everybody is using one of our clients (JSX/CLI/Mobile) which all define transactions like good boys.

Now that this bug (feature?:) is detected however, one might actually wonder if this "opt-out" experience is really so bad. Normally these fees are to help incentivize the block creators to:

1) include the transaction in a block
2) if too many transactions are available to include, take the highest paid ones

In our case however the transaction fees go for **100%** to the TF Foundation, and thus I wonder if it is such a bad idea to keep it opt-out.

Either way, this became an open question out of the blue that we should fix ASAP.

**Comment by robvanmieghem** [comment]
@GlenDC no, it is not: https://github.com/threefoldtech/rivine/blob/master/doc/new_chain/transactionfees.md
