### ISSUE TITLE
Check for block creation transactions fails in case of a fork

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#523]
Since we enfore a minerfee except for the block creation txes, we must check for every transaction if it is indeed a block creation tx for the validation context. Part of this check is verifyinig if a blockstake respent is indeed as expected according to the header. However if there is a fork in the network, and the bs output which is being used is in the innactive fork (for this node), the check fails, since the header points to a block height (thus the active fork)

**Comment by robvanmieghem** [comment]
@LeeSmet What is the functional consequence of this?

**Comment by LeeSmet** [comment]
A daemon which has the mentioned fix will reject all block creation transactions which reference a blockstakeoutput in an inactive fork, meaning as soon as there is a fork of more than one block, it might be rejected outright, causing network separation

**Comment by LeeSmet** [comment]
Fixed in 352f22c25b371bc62fdec90cfcd0821e65cf30cf
