### ISSUE TITLE
create FFT chain

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#533]

**Comment by GlenDC** [comment]
I propose we block this issue until https://github.com/threefoldtech/rivine/issues/555 is finished and Rivine 1.2 is stable. Please read https://github.com/threefoldtech/rivine/issues/555 for more information.

**Comment by GlenDC** [comment]
Launched and testnet is available. A local devnet can be used as well.

Repo: <http://github.com/threefoldtech/FFTchain>
Public Testnet Explorer: <http://explorer.testnet.fft.threefold.tech>
