### ISSUE TITLE
create TFB chain

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#534]
Create & Launch the TFB chain all networks operational, step by step:

- [x] delete repo <https://github.com/threefoldtech/TFBchain> and make it a repo created from the following template: <https://github.com/threefoldtech/rivine-chain-template>
- [x] adapt code as instructed in the README of the code provided by the template
- [x] once your chain is up and running (test using devnet) with no features added, adapt the template so that future chains (e.g. #533) can be created more easily
- [x] add and enable the minting extension: test again on devnet and confirm it works (e.g. that you can mint and use all it other features, leave out the opt-in burn transaction for now...)
- [x] request @leesmet to help and provide 1 or 2 DNS names for TESTNET bootstrap peers and explorers
- [x] configure and enable testnet (using these bootstrap peers and explorers)
- [x] test & validate
- [x] request @leesmet to help and provide 1 or 2 DNS names for STANDARD NETWORK bootstrap peers and explorers
- [x] launch, test & validate

**Comment by robvanmieghem** [comment]
repo:https://github.com/threefoldtech/TFBchain

**Comment by GlenDC** [comment]
I propose we block this issue until https://github.com/threefoldtech/rivine/issues/555 is finished and Rivine 1.2 is stable. Please read https://github.com/threefoldtech/rivine/issues/555 for more information.

**Comment by GlenDC** [comment]
Launched and testnet is available. A local devnet can be used as well.

Repo: <http://github.com/threefoldtech/TFBchain>
Public Testnet Explorer: <http://explorer.testnet.tfb.threefold.tech>
