### ISSUE TITLE
prepare 5 nodes on Ghent dc for bc testnets

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#535]

**Comment by LeeSmet** [comment]
We'll need the following:

 - [ ] Set up new private zerotier network for management
 - [ ] Get 5 nodes from dc
   - [ ] Get nodes, write down serials so they can be removed from stock/backend
   - [ ] Retrieve possible coins/blockstakes on the nodes, if any
   - [ ] Disable secure boot if enabled
   - [ ] Rewrite USB's to boot latest master of zero-os
 - [ ] Create 0-robot templates
   - [ ] Get repo for templates
 - [ ] flists which contain the right binaries
 - [ ] IP address - 1 per container

Once we have all that we can do the initial setup and deployment

**Comment by LeeSmet** [comment]
Zerotier network has been set up: `a84ac5c10ab0d01f`

**Comment by LeeSmet** [comment]
Nodes taken from DC:

| Serial number | Id |
| --- | --- |
| HYSZ170000794 | 00e04c6804a9 |
| HYSZ170000755 | 00e04c680a2d |
| HYSZ170000783 | 00e04c680321 |
| HYSZ170000694 | 00e04c680585 |
| HYSZ170000787 | 00e04c6805f8 |

**Comment by LeeSmet** [comment]
IYO organization: `goldchain`
flist: https://hub.grid.tf/goldchain/goldchain-latest.flist.md

@GlenDC and @robvanmieghem have been invited as owners of the IYO org to have some redundancy as well

**Comment by LeeSmet** [comment]
Testnet for goldchain is live

5 bootstrap nodes: 2 explorers / 3 block creators

faucet / authorizer to be developed & deployed later on fruit-jr
