### ISSUE TITLE
AuthCoins: sending coins from an unauthorized address should not return a 500

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#541]
500 indicates a server (code) error whereas this is more of a user error.

Suggestion: 401 Unauthorized

**Comment by GlenDC** [comment]
Block stakes require no authorized address, it is coins that requires authorized addresses.

Does it require coins (for miner fees) to transfer block stakes? if so, than that is your error. Could you please confirm, and if true change the title as well to refer to the transfer of coins.

**Comment by GlenDC** [comment]
It does make me wonder if we shouldn't allow the situations where your coin inputs are only used for miner fees and a refund coin output to the same address as (one of) the coin inputs, without require authorisation.

**Comment by LeeSmet** [comment]
Indeed the problem was the sending address was not authorized
