### ISSUE TITLE
authcoin: Wrong address is identified as unauthorized when the sender is not authorized

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#550]
```
goldchainc wallet send coins 017d8b80d279dc691f3d1af12a6419bde0738e4d3bb406371756a77b657841a0c06c206c98c8a9 300000
Could not send coins: HTTP 403 error: error after call to /wallet/coins: User Error forbidden: unauthorized address 017d8b80d279dc691f3d1af12a6419bde0738e4d3bb406371756a77b657841a0c06c206c98c8a9 cannot participate in a coin transfer
```

In the above command, the receiver was previously authorized, but the sender was not. Still the error claims the receiver is unauthorized. After authorizing the sender, the transaction succeeded

**Comment by GlenDC** [comment]
I think this was wrongfully reported. If you encounter it again, please attach:

- output of `goldchainc consensus`
- for each address involved in the transaction: `goldchainc explore authcoin <address>`
