### ISSUE TITLE
simplify transactionpool by keeping only a single set of transactions

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/rivine#563]
Currently we keep a set of transaction sets. Each transaction added to the txpool is added as a separate tx set. This works fine for the standard rules as all objects (transactions, output, inputs) are kept as known objects and in case such an object is spent (meaning it is known in tx pool and thus still unconfimed) than the transactions will be merged together and validated as a whole, allowing this behaviour.

As soon as you add new rules to the mix though, it doesn't play well with it, given it does not notice any ID-based conflicts and thus keeps them separate.

If instead we keep all transactions in a single set, we will at all times have a full view of the tx set and thus we will be able to handle unconfirmed objects to be spent as well as any other rules that apply to tx dependency.

We do need to guarantee that tx order is respected in terms of the dependency tree. Currently that would be guaranteed, but if we implement priority ordering in the future this would need to be respected as a master rule.

**Comment by GlenDC** [comment]
Discussion that triggered this proposal can be found at https://github.com/nbh-digital/goldchain/issues/36#issuecomment-515878182 (and the comments surrounding it).

**Comment by robvanmieghem** [comment]
As discusssed with the problem of the blockcreator removing the transactions from the pool, I wonder if it is the task of the blockcreator.
When the block is accepted in the consensus, the transactions are removed from the pool anyway.

**Comment by GlenDC** [comment]
I think you are right. Did a quick checkup and it does seem that we can just remove them automatically when receiving them as part of the `ProcessConsensusChange` callback the TxPool has implemented as part of its contract for being a ConsensusSet subscriber. Will just need to ensure that its TxPool subscribers are aware of this removal from the pool as well.

**Comment by GlenDC** [comment]
Going to keep this issue really simple. It can get out of scope very quickly, potentially breaking code without giving much benefits. Point is that there is a lot that can be improved in the txpool, but these should be separate issues. 

I did already remove the purging from the code, as I do agree that this should not be done by the consensus.

But removing the txpool set or even sets of sets from the codebase might not be necessary for this issue. It could be a nice thing to do, but it's quite invasive and is not required for resolving this issue.

All we care for this issue is that we do not take care of related objects, and based on that validate the tx set on its own or within a greater context. Instead we want to validate based on everything always (everything meaning the current consensus state and tx pool state combined).

**Comment by GlenDC** [comment]
`PurgeTransactionPool()` method of the TransactionPool interface and its use by the BlockCreator (our miner) was added and used again since commit c047b23619d4e512a7f14b95f0f706631209bb87. Turns out that due to possible buggy behaviour when there is a lot of traffic, it does become necessary to not completely block that block creator to an indefinite halt.
