### ISSUE TITLE
Block validation is slow

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#580]
https://github.com/nbh-digital/goldchain/issues/48

**Comment by LeeSmet** [comment]
As a first step, remove the database reads when calculating the stake modifier by creating a cache of block ids and their parent ids

**Comment by LeeSmet** [comment]
Perhaps it is also possible to cache things like blockstake outputs (as those are always limited and used for every block) to further increase the speed of block validations

**Comment by LeeSmet** [comment]
First improvements done in #595. Calculating the stake modifier now no longer requires massive amounts of database reads

**Comment by LeeSmet** [comment]
Added some more caching, for caclulating a blocks minimum timestamp. It might also be worthhile to look at caching the blockstake outputs (since there is at least one used every block to validate said block) and a part of the coin outputs (lazily as blocks get validated?). For the latter, we might first want to look at some data to see if recent coin outputs are more likely to then be spent again soon after they are created.

**Comment by GlenDC** [comment]
> and a part of the coin outputs

not really convinced that you can really cache smart here, but looking at some data can never hurt I suppose

**Comment by LeeSmet** [comment]
For now let's first check how the current improvements impact performance in field nodes on multiple chains

**Comment by robvanmieghem** [comment]
@LeeSmet Do you have an update on this?

**Comment by LeeSmet** [comment]
For now the syncing time has significantly improved compared to the previous version. It seems the problems are now mostly arising from the database and encoding. It seems worthwhile to investigate different storage solutions in the future to this end
