### ISSUE TITLE
Use modern (vuejs) explorer for rivine example chain

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/rivine#607]
- [x] finish development of the vuejs explorer: https://github.com/threefoldtech/rivine-chain-explorer/projects/1
- [ ] use it for the rivine chain example

**Comment by DylanVerstraete** [comment]
Development for generic explorers are done. We can now move to testing phase.

**Comment by robvanmieghem** [comment]
ae78958438c24879b8473aaae1f641de00d20763
