### ISSUE TITLE
Research how a rivine private key can be used in Stellar

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#618]

**Comment by zaibon** [comment]
@robvanmieghem 
Regarding this task. Can we create a clear list of all the feature we want to be able to have when/if switching to stellar. 
I just want us to be fully prepared and 100% sure all of our use case will be possible and not too hard to implement before we make a move.

**Comment by robvanmieghem** [comment]
@zaibon  You are absolutely right, I was going to write a separate document about that.
This issueis more for the Jimber guys to check how they can reuse their existing logic.
I also wanted to check if Rivine addresses derived from Stellar account addresses and vice versa. This issue is  no story but more a part of the  story you describe above

**Comment by robvanmieghem** [comment]
f86d70334a3d6d245358ee27ad20a7baf6bdf581
